default-resources:
    mem_mb_per_cpu: 10000
    runtime: 1d
    qos: default
    threads: 12
    partition: normal
set-threads:
    concatenate_nanopore: 1
    concatenate_pacbio: 1
    extract_longest: 1
